import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import kanBan from "../../public/KanBan.png";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Kan-Ban!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles.content}>
        <div>
          <h1 className={styles.title}>Make your life easier!</h1>
          <p>
            Notion is the connected workspace where better, faster work happens.
          </p>
        </div>

        <div style={{ display: "flex" }}>
          <Link href={"/register"} className="blackLink">
            <p>Use Kan-Ban! for Free</p>
          </Link>
        </div>
        <Image
          priority
          className={styles.image}
          width={613}
          height={437}
          src={kanBan}
          alt="KanBan Photo"
        />
        
      </section>
    </>
  );
}
